// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imwakphuozijevhjetyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imltd2FrcGh1b3ppamV2aGpldHlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTE2OTEsImV4cCI6MjA2NjUyNzY5MX0.iIMTp_mXFds6eatn6DHacO3k72bu6WpXLMdpRkUwkCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);